# User config
author: "Uyen Le"
tagline: ""
description: ""
keywords: ""
email: "hellouyenle@gmail.com"
instagram: "https://instagram.com/uyenlex"
linkedin: "https://www.linkedin.com/in/uyenle57"
twitter: "https://twitter.com/uyenlex"
github: "https://github.com/uyenle57"

#Site navigation
about: "about"
illustrations: "illustrations"
computing: "computing"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
