# User config
author: "Uyen Le"
tagline: ""
description: ""
keywords: ""
email: "hellouyenle@gmail.com"
instagram: "https://instagram.com/uyenlex"
twitter: "https://twitter.com/uyenlex"
github: "https://github.com/uyenle57"
behance: "https://behance.net/uyenle"

#Site navigation
about: "About"
illustrations: "Illustrations"
computing: "Computing"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
